### ISSUE TITLE
Properly support alternating font face tags like .BR and .RB

### ISSUE THREAD

**Issue by dmiller-nmap** [bagder/roffit#10]
Currently, `.BR` tags are treated as lists of manpage links, which are rendered in boldface, connected by commas. This is frequently how this tag is used, but it is not actually what it means, and there are a series of other tags with similar meanings that could be supported, too.

The meaning of `.BR` is, [according to `groff(7)`](https://manpages.debian.org/jessie/groff/groff_man.7.en.html), "Causes text on the same line to appear alternately in bold face and roman." This means that a line like:

    .BR a b c d

Should be rendered as "**a** b **c** d". Similarly, `.RB` is alternate roman and bold face, so the same line would be "a **b** c **d**". There are also tags for alternating italic and roman (`.RI`, `.IR`), and bold and italic (`.BI`, `.IB`).

Once this is implemented, I think the `linkfile` subroutine will be able to sufficiently check for links if necessary, so that part can be stripped from the existing `.BR` handler.

**Comment by dmiller-nmap** [comment]
There's an additional complication in that text in quotes is supposed to be treated as a single token, so:

    .BR a "b c" d

Should render as "**a** b c **d**"

**Comment by dmiller-nmap** [comment]
Of course, this makes the `linkfile` subroutine have to do a bit more searching, since the `(section)` portion is separate from the identifier. Here's the example roff code I'm looking at:

```roff
.PP
.B pcap_sendpacket()
is like
.BR pcap_inject() ,
but it returns 0 on success, rather than returning the number of bytes
written.
.RB ( pcap_inject()
comes from OpenBSD;
.B pcap_sendpacket()
comes from WinPcap.  Both are provided for compatibility.)
```

And of course here is a more typical example:

```roff
.SH SEE ALSO
.BR bind (2),
.BR connect (2),
.BR listen (2),
.BR select (2),
.BR socket (2),
.BR socket (7)
```

**Comment by bagder** [comment]
Do you happen to have a man page or two somewhere that use these formats? I figure that would be good when working out this.

I also think it's time to add some test cases that we can run to make sure there aren't any regressions when we change things...

**Comment by bagder** [comment]
> I'm thinking about starting this myself as a PR

Lovely, thanks!

> Do you have any aversion to dependencies on other Perl packages?

Not really, no. Just as long as they're reasonably "established" and they offer a clear benefit to the program!
