### ISSUE TITLE
text mismatch between documentation and generated output in curl

### ISSUE THREAD

**Issue by sairam** [bagder/roffit#23]
https://example.com is split across multiple locations making it syntactically incorrect.

impacted page: https://curl.se/libcurl/c/CURLOPT_REQUEST_TARGET.html

source compared to: https://github.com/curl/curl/blob/master/docs/libcurl/opts/CURLOPT_REQUEST_TARGET.3#L41

**screen shot of image:** 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/163584/105471427-bb40e280-5cc0-11eb-9039-d37e030ebd2a.png">

code from source code: 
```
<pre class="level0">
curl = curl_easy_init();
if(curl) {
&nbsp; curl_easy_setopt(curl, CURLOPT_URL, &quot;https://example./*&quot;);
&nbsp; curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, &quot;OPTIONS&quot;);
&nbsp;
&nbsp; /* issue an OPTIONS * request (no leading slash) */com
&nbsp; curl_easy_setopt(curl, CURLOPT_REQUEST_TARGET, &quot;*&quot;);
&nbsp;
&nbsp; /* Perform the request */
&nbsp; curl_easy_perform(curl);
}
</pre>
```

**Comment by jay** [comment]
I can't reproduce this with roffit master (b59e6c8 2019-12-13) so if it was a bug it's been fixed. The page needs to be regenerated. Thanks

**Comment by sairam** [comment]
the  page was last generated after Nov 4, 2020 based on the commit/changes in curl.

> Latest commit 4d2f800 on Nov 4, 2020

**Comment by jay** [comment]
I'm going to reopen this until the page is fixed so we don't forget about it.

**Comment by bagder** [comment]
It's not a roffit bug, it's a bug in the curl site build scripts. I'm on it.

**Comment by bagder** [comment]
Fixed!
