### ISSUE TITLE
roffit takes some characters that should be ignored

### ISSUE THREAD

**Issue by hydrargyrum** [bagder/roffit#28]
Debian's manpages (for example [ls](https://manpages.debian.org/bullseye/coreutils/ls.1.en.gz)) contain `,` and `/` that seem to have a markup role (italic?) around some words. Here's how it could render for example [on debian site](https://manpages.debian.org/bullseye/coreutils/ls.1.en.html).

But roffit renders them literally:

```
<p class="level0"><span Class="bold">ls</span> [<span Class="emphasis">,OPTION/</span>]... [<span Class="emphasis">,FILE/</span>]... <a name="DESCRIPTION"></a><h2 class="nroffsh">DESCRIPTION</h2>
```

**Comment by bagder** [comment]
It think it is `\,` and `\/` that are special. I'm reading https://n-t-roff.github.io/heirloom/doctools/troff.pdf and on page 58 it says:

> The `\/` escape sequence inserts an italic correction, i.e. a small piece of horizontal motion (1/12 em) that should be
sufficient to separate an italic character from a following roman character. Similarly, `\,` adds a left italic correction,
always a zero motion, that should be sufficient to separate a roman character from an immediately following italic
character.

**Comment by bagder** [comment]
Any chance you can try #29 and see if it fixes the issue?
