### ISSUE TITLE
missing </p> tags

### ISSUE THREAD

**Issue by 1268** [bagder/roffit#38]
the anchors are there, but the HTML is malformed:

~~~html
<p class="level0">curl attempts to re-use connections when doing multiple file
transfers, so that getting many files from the same server do not use multiple
connects / handshakes. This improves speed. Connection re-use can only be done
for URLs specified for a single command line invocation and cannot be performed
between separate curl runs. <a name="OUTPUT"></a>
<h2 class="nroffsh">Output</h2>
~~~

notice carefully that the `</p>` is missing. this page:

https://curl.se/docs/manpage.html

docs:

- https://developer.mozilla.org/docs/Web/HTML/Element/p
- https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element

**Comment by 4cq2** [comment]
https://github.com/curl/curl/issues/11406

**Comment by 4cq2** [comment]
https://github.com/bagder/roffit/blob/26d34eb7dbfa42f52d3cdc14e57a85f40d61033c/roffit#L102-L103
